{
    "zh_CN":{
        "ui.screenplayAgentInspector.__gaze":"视线交互",
        "ui.screenplayAgentInspector.__gazeAliasField":"触发器名称"
    },
    "en_US":{
        "ui.screenplayAgentInspector.__gaze":"Gaze",
        "ui.screenplayAgentInspector.__gazeAliasField":"Alias"
    }
}
