{
    "en_US":{
        "ui.loadingtip.init_license":"initialize plugin license",
        "ui.loadingtip.verify":"verify",
        "ui.loadingtip.needverify":"needverify",
        "ui.loadingtip.preload_plugins":"preload plugins",
        "ui.loadingtip.init_bucket":"initialize plugin bucket",
        "ui.loadingtip.init_bean":"initialize plugin bean",
        "ui.loadingtip.register_bean_source":"register sources",
        "ui.loadingtip.init_diagram":"initialize plugin diagram",
        "ui.loadingtip.init_canvas":"initialize plugin canvas",
        "ui.loadingtip.init_screenplay":"initialize plugin screenplay",
        "ui.loadingtip.preload_plugins_success":"preload plugins success",
        "ui.loadingtip.wait_canvas_ready":"waiting for the canvas to be ready ...",
        "ui.loadingtip.unityready":"canvas ready"
    },
    "fr": {
                 "ui.loadingtip.init_license": "initialiser la licence du plugin",
                 "ui.loadingtip.verify": "vérifier",
                 "ui.loadingtip.needverify": "needverify",
                 "ui.loadingtip.preload_plugins": "plugins de précharge",
                 "ui.loadingtip.init_bucket": "initialiser le compartiment du plugin",
                 "ui.loadingtip.init_bean": "initialize bean plugin",
                 "ui.loadingtip.register_bean_source": "register sources",
                 "ui.loadingtip.init_diagram": "initialise le diagramme du plugin",
                 "ui.loadingtip.init_canvas": "initialiser le canevas du plugin",
                 "ui.loadingtip.init_screenplay": "initialiser le scénario du plugin",
                 "ui.loadingtip.preload_plugins_success": "succès des plugins de préchargement",
                 "ui.loadingtip.wait_canvas_ready": "dans l'attente que la toile soit prête ...",
                 "ui.loadingtip.unityready": "toile prête"
    },
    "jp"：{
                 "ui.loadingtip.init_license"： "プラグインライセンスの初期化",
                 "ui.loadingtip.verify"： "確認",
                 "ui.loadingtip.needverify"： "needverify",
                 "ui.loadingtip.preload_plugins"： "プリロードプラグイン",
                 "ui.loadingtip.init_bucket"： "プラグインバケットの初期化",
                 "ui.loadingtip.init_bean"： "プラグインBeanの初期化",
                 "ui.loadingtip.register_bean_source"： "ソース登録",
                 "ui.loadingtip.init_diagram"： "プラグイン図の初期化",
                 "ui.loadingtip.init_canvas"： "プラグインキャンバスの初期化",
                 "ui.loadingtip.init_screenplay"： "プラグインのスクリーンプレイを初期化する",
                 "ui.loadingtip.preload_plugins_success"： "プリロードプラグインの成功",
                 "ui.loadingtip.wait_canvas_ready"： "キャンバスの準備ができているのを待っています...",
                 "ui.loadingtip.unityready"： "キャンバス準備完了"
    },
    "sp": {
                 "ui.loadingtip.init_license": "inicializar licencia de complemento",
                 "ui.loadingtip.verify": "verificar",
                 "ui.loadingtip.needverify": "needverify",
                 "ui.loadingtip.preload_plugins": "preload plugins",
                 "ui.loadingtip.init_bucket": "initialize plugin bucket",
                 "ui.loadingtip.init_bean": "inicializar plugin bean",
                 "ui.loadingtip.register_bean_source": "registrar fuentes",
                 "ui.loadingtip.init_diagram": "inicializar diagrama de plugin",
                 "ui.loadingtip.init_canvas": "inicializar el lienzo del complemento",
                 "ui.loadingtip.init_screenplay": "initialize plugin screenplay",
                 "ui.loadingtip.preload_plugins_success": "éxito de carga de complementos",
                 "ui.loadingtip.wait_canvas_ready": "esperando que el lienzo esté listo ...",
                 "ui.loadingtip.unityready": "canvas ready"
    },
    "it": {
                 "ui.loadingtip.init_license": "inizializza la licenza del plugin",
                 "Ui.loadingtip.verify": "verifica",
                 "Ui.loadingtip.needverify": "needverify",
                 "ui.loadingtip.preload_plugins": "plug-in precaricamento",
                 "ui.loadingtip.init_bucket": "inizializza bucket plugin",
                 "ui.loadingtip.init_bean": "inizializza bean plugin",
                 "ui.loadingtip.register_bean_source": "registra fonti",
                 "ui.loadingtip.init_diagram": "inizializza il diagramma del plugin",
                 "ui.loadingtip.init_canvas": "inizializza il canvas del plugin",
                 "ui.loadingtip.init_screenplay": "inizializza la sceneggiatura del plugin",
                 "ui.loadingtip.preload_plugins_success": "preload plugins success",
                 "ui.loadingtip.wait_canvas_ready": "in attesa che la tela sia pronta ...",
                 "ui.loadingtip.unityready": "canvas ready"
    },
    "kr": {
                 "ui.loadingtip.init_license": "플러그인 라이센스 초기화",
                 "ui.loadingtip.verify": "확인",
                 "ui.loadingtip.needverify": "needverify",
                 "ui.loadingtip.preload_plugins": "미리로드 된 플러그인",
                 "ui.loadingtip.init_bucket": "플러그인 버킷 초기화",
                 "ui.loadingtip.init_bean": "초기화 플러그인 콩",
                 "ui.loadingtip.register_bean_source": "소스 등록",
                 "ui.loadingtip.init_diagram": "플러그인 다이어그램 초기화",
                 "ui.loadingtip.init_canvas": "초기화 플러그인 캔버스",
                 "ui.loadingtip.init_screenplay": "초기화 플러그인 플러그인"
                 "ui.loadingtip.preload_plugins_success": "사전로드 플러그인 성공",
                 "ui.loadingtip.wait_canvas_ready": "캔버스가 준비 될 때까지 기다리는 중 ...",
                 "ui.loadingtip.unityready": "캔버스 준비 완료"
    },
    "pt": {
                 "ui.loadingtip.init_license": "inicializar a licença do plug-in",
                 "ui.loadingtip.verify": "verify",
                 "ui.loadingtip.needverify": "needverify",
                 "ui.loadingtip.preload_plugins": "plugins de pré-carregamento",
                 "ui.loadingtip.init_bucket": "inicializar o depósito do plug-in",
                 "ui.loadingtip.init_bean": "inicializar o bean de plugin",
                 "ui.loadingtip.register_bean_source": "registrar fontes",
                 "ui.loadingtip.init_diagram": "inicializar o diagrama do plugin",
                 "ui.loadingtip.init_canvas": "inicializar a tela do plugin",
                 "ui.loadingtip.init_screenplay": "inicializar o roteiro do plugin",
                 "ui.loadingtip.preload_plugins_success": "pré-carregamento de plugins",
                 "ui.loadingtip.wait_canvas_ready": "esperando que a tela esteja pronta ...",
                 "ui.loadingtip.unityready":"tela pronta"
    },
    "zh_TW":{
        "ui.loadingtip.init_license":"初始化插件許可證",
        "ui.loadingtip.verify":"驗證",
        "ui.loadingtip.needverify":"未授權",
        "ui.loadingtip.preload_plugins":"載入插件",
        "ui.loadingtip.init_bucket":"初始化資源插件",
        "ui.loadingtip.init_bean":"初始化项目插件",
        "ui.loadingtip.register_bean_source":"註冊擴展包",
        "ui.loadingtip.init_diagram":"初始化藍圖插件",
        "ui.loadingtip.init_canvas":"初始化渲染插件",
        "ui.loadingtip.init_screenplay":"初始化劇本插件",
        "ui.loadingtip.preload_plugins_success"："加載插件成功",
        "ui.loadingtip.wait_canvas_ready":"等待渲染就緒",
        "ui.loadingtip.unityready":"渲染就緒"
    },
    "zh_CN":{
        "ui.loadingtip.init_license":"初始化授权插件",
        "ui.loadingtip.verify":"验证授权",
        "ui.loadingtip.needverify":"未授权",
        "ui.loadingtip.preload_plugins":"加载插件",
        "ui.loadingtip.init_bucket":"初始化资源插件",
        "ui.loadingtip.init_bean":"初始化项目插件",
        "ui.loadingtip.register_bean_source":"注册扩展包",
        "ui.loadingtip.init_diagram":"初始化蓝图插件",
        "ui.loadingtip.init_canvas":"初始化渲染插件",
        "ui.loadingtip.init_screenplay":"初始化剧本插件",
        "ui.loadingtip.preload_plugins_success":"加载插件成功",
        "ui.loadingtip.wait_canvas_ready":"等待渲染就绪",
        "ui.loadingtip.unityready":"渲染就绪"
    }
}
